# Site settings
title: robert3d
email: robert3d@gmail.com
description: "Adventures in learning new skills."
baseurl: ""
url: "http://robert3d.github.io"

# Build settings
markdown: kramdown
permalink: pretty
